Best Practises
1. Preprocessing and Cleaning
2. Train test split
3. bow tfidf word2vec
4. Train Ml algo

In [20]:
import pandas as pd
data = pd.read_csv('data.csv')

In [33]:
data.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       3
1  great short read didnt want put read one sitti...       5
2  ill start saying first four books wasnt expect...       3
3  aggie angela lansbury carries pocketbooks inst...       3
4  expect type book library pleased find price right       4

In [22]:
data=data[['reviewText' , 'rating']]

In [6]:
data.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [7]:
data.shape

(12000, 2)

In [8]:
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [34]:
#postive review is 1 and negative is 0


data['rating']=data['rating'].apply(lambda x: 0 if x<3 else 1)

In [24]:
## lower all cases
data['reviewText']=data['reviewText'].str.lower()

In [35]:
data.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [39]:
## removing special characters
import re
import nltk
from nltk.corpus import stopwords
from nltk import wordnet

In [25]:
data['reviewText']=data['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9]+' , '' , x))

In [27]:
data['reviewText']=data['reviewText'].apply(lambda x : " ".join([y for y in x.split() if y not in stopwords.words('english')]))

In [30]:
data.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       3
1  great short read didnt want put read one sitti...       5
2  ill start saying first four books wasnt expect...       3
3  aggie angela lansbury carries pocketbooks inst...       3
4  expect type book library pleased find price right       4

In [43]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lakshya\AppData\Roaming\nltk_data...

In [44]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [45]:
data['reviewText'] = data['reviewText'].apply(lambda x : lemmatize_words(x))

In [46]:
data.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train,X_test,y_train,y_test=train_test_split(data['reviewText'],data['rating'], test_size=.2)